import { NewProject, objKeyAsString } from 'utils/customTypes';

export const defaultNewProjectData: NewProject = {
  title: '',
  businessUnitId: '',
  category_id: '',
  description: '',
  startDate: null,
  actualDate: null,
  targetCompletionDate: null,
  targetLaunchDate: null,
  process_id: '',
  status: '',
  stage_id: '',
  privacy: '',
  learningTeams: [],
  priority: null,
  owners: [],
  resourcing_type: null,
  estimatedEffort: '',
  budget_source: null,
  estimated_cost: '',
  allocated_budget: 0,
  health: '',
  projectRequests: [],
  hold_reason: '',
  vendors: [],
  actual_cost: 0,
  actual_time_spent: 0,
  finalComments: '',
  closedDate: null,
  tasksOrdering: [],
};

export const requiredFields = [
  'title',
  'category_id',
  'businessUnitId',
  'owners',
  'startDate',
  'targetCompletionDate',
  'privacy',
  'process_id',
  'stage_id',
  'status',
];

export const requiredFieldsErrorsMap: objKeyAsString = {
  title: false,
  category_id: false,
  businessUnitId: false,
  owners: false,
  startDate: false,
  targetCompletionDate: false,
  privacy: false,
  process_id: false,
  stage_id: false,
  status: false,
};
