name: Cypress e2e run

on:
  push
  # pull_request:
  #   branches:
  #     - develop

jobs:
  cypress-run:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2

      - name: Cypress run chrome
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npx serve -s build -l 3005
          spec: 'cypress/integration/TestPhase/test-spec.js'
          record: true
        env:
          CYPRESS_RECORD_KEY: bb48e66f-0528-4777-a79f-0681517c0fa3
          COGNITO_URL: https://cognito-idp.us-east-1.amazonaws.com/
          USER_EMAIL: alex+test@getsynapse.com
          USER_PASSWORD: EKtest1#
          USER_NAME: Richard Tester
          COGNITO_USER_POOL_ID: us-east-1_nl3w1caiU
          COGNITO_USER_POOL_WEB_CLIENT: 1spbfikl1vtlfmrpevdqjds2f8
          DOMAIN_NAME: localhost
          secureCookie: false

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      # - name: Cypress run edge
      #   uses: cypress-io/github-action@v2
      #   with:
      #     spec: '**/Auth/*'
